### ISSUE TITLE
Set a different "reply to" email address

### ISSUE THREAD

**Issue by diggeridoo** [valeriosouza/my-smtp-wp#1]
I use a general mail address to site's administrative tasks and notifications, but I don't want this address appears in the "reply to" field to the general public. 
With other plugins is possible to differentiate between this two fields "sent by" and "reply to" with different emails in order to keep tidy the communications.
Could this be implemented for My-Smtp-WP?
It would be very useful!

Thanks

**Comment by GermanKiwi** [comment]
+1

**Comment by valeriosouza** [comment]
new in version 1.1 2c4a6c6a3d1068e4f067a3242d466ffc7942f17e
